apiVersion: v1
kind: Pod
metadata:
  name: agentPod
  labels:
    app: agentPod
spec:
  containers:  
  - name: docker
    image: docker:19.03.1
    env:
      - name: DOCKER_HOST
        value: tcp://localhost:2375
    readinessProbe:
      exec:
        command: [sh, -c, "ls -S /var/run/docker.sock"]
    command:
    - sleep
    args:
    - 99d
    volumeMounts:
    - name: docker-socket
      mountPath: /var/run
  - name: docker-daemon
    image: docker:19.03.1-dind
    env:
      - name: DOCKER_TLS_CERTDIR
        value: ""
    securityContext:
      privileged: true
    volumeMounts:
    - name: cache
      mountPath: /var/lib/docker
  volumes:
  - name: cache
    hostPath:
      path: /tmp
      type: Directory
