apiVersion: v1
kind: Pod
metadata:
  name: agentPod
  labels:
    app: agentPod
spec:
  containers:  
  - name: docker
    image: docker:19.03.1
    readinessProbe:
      exec:
        command: [sh, -c, "ls -S /var/run/docker.sock"]
    command:
    - sleep
    args:
    - 99d
    volumeMounts:
    - name: docker-socket
      mountPath: /var/run
  - name: docker-daemon
    image: docker:19.03.1-dind
    securityContext:
      privileged: true
    volumeMounts:
    - name: docker-socket
      mountPath: /var/run
    - name: maven
      image: maven:latest
      command:
        - cat
      tty: true
      volumeMounts:
        - name: m2
          mountPath: /root/.m2
  volumes:
    - name: docker-socket
      emptyDir: {}
    - name: m2
      hostPath:
        path: /root/.m2
