apiVersion: v1
kind: Pod
metadata:
  name: img
  annotations:
    container.apparmor.security.beta.kubernetes.io/img: unconfined  
spec:
  containers:
  - name: kaniko
    image: gcr.io/kaniko-project/executor:v1.6.0-debug
    imagePullPolicy: Always
    command:
    - sleep
    args:
    - 99d
    volumeMounts:
    - name: jenkins-docker-cfg
      mountPath: /kaniko/.docker
volumes:
- name: jenkins-docker-cfg
  projected:
    sources:
    - secret:
        name: regcred
        items:
          - key: .dockerconfigjson
            path: config.json
