apiVersion: v1
kind: Pod
metadata:
  name: img  
spec:
  containers:
  - name: kaniko
    image: gcr.io/kaniko-project/executor:v1.6.0-debug
    imagePullPolicy: Always
    command:
    - sleep
    args:
    - 99d
    volumeMounts:
    - name: kanikocfg
      mountPath: /kaniko/.docker
volumes:
- name: kanikocfg
  projected:
    sources:
    - secret:
        name: regcrednex
        items:
          - key: .dockerconfigjson
            path: config.json
